version: '2'
services:
  db:
    image: $db_image
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  odoo:
    image: $odoo_image
    depends_on:
      - db
    volumes:
      - odoo-web-data:/var/lib/odoo
      #- ./config:/etc/odoo
      #- ./addons:/mnt/extra-addons
  nginx:
    image: $nginx_image
    depends_on:
      - odoo
    #restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-logs:/var/log/nginx
      - ./nginx-conf:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
volumes:
  odoo-db-data:
  odoo-web-data:
  nginx-logs:
